export const SELECT_ENTRIES_STATUS = 'SELECT_ENTRIES_STATUS';
export const REQUEST_CURRENT_WEATHER = 'REQUEST_CURRENT_WEATHER';
export const RECEIVE_CURRENT_WEATHER = 'RECEIVE_CURRENT_WEATHER';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const UPDATE_CURRENT_WEATHER_ENTRY = 'UPDATE_CURRENT_WEATHER_ENTRY';
export const MOVE_CURRENT_WEATHER = 'MOVE_CURRENT_WEATHER';
